// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_HOST_SUFFIX = ".supabase.co";

function getServerEnv(name: string) {
  if (typeof process === "undefined") return undefined;
  return process.env[name];
}

function normalizeSupabaseProjectRef(value: string | undefined) {
  if (!value) return undefined;

  const trimmed = value.trim();
  if (!trimmed) return undefined;

  try {
    const parsed = new URL(trimmed.includes("://") ? trimmed : `https://${trimmed}`);
    if (parsed.hostname.endsWith(SUPABASE_HOST_SUFFIX)) {
      return parsed.hostname.slice(0, -SUPABASE_HOST_SUFFIX.length);
    }
  } catch {
    // Fall back to treating the value as a raw project ref below.
  }

  return trimmed
    .replace(SUPABASE_HOST_SUFFIX, "")
    .replace(/^https?:\/\//, "")
    .replace(/\/$/, "");
}

function normalizeSupabaseUrl(value: string | undefined) {
  if (!value) return undefined;

  const trimmed = value.trim().replace(/\/$/, "");
  if (!trimmed) return undefined;

  if (!trimmed.includes("://")) {
    return `https://${normalizeSupabaseProjectRef(trimmed)}${SUPABASE_HOST_SUFFIX}`;
  }

  return trimmed;
}

function resolveSupabaseUrl() {
  const configuredProjectRef = normalizeSupabaseProjectRef(
    import.meta.env.VITE_SUPABASE_PROJECT_ID || getServerEnv("SUPABASE_PROJECT_ID"),
  );
  if (configuredProjectRef) return `https://${configuredProjectRef}${SUPABASE_HOST_SUFFIX}`;

  return normalizeSupabaseUrl(import.meta.env.VITE_SUPABASE_URL || getServerEnv("SUPABASE_URL"));
}

function createSupabaseClient() {
  // Prefer the project id when it is available so preview/production builds cannot
  // accidentally keep talking to a stale Supabase project URL.
  const SUPABASE_URL = resolveSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || getServerEnv("SUPABASE_PUBLISHABLE_KEY");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL or SUPABASE_PROJECT_ID"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Fehlende Supabase-Umgebungsvariable(n): ${missing.join(", ")}. Bitte konfiguriere die erforderlichen Supabase-Umgebungsvariablen.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
